// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: models/todo.proto

package TodoGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_models_todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_models_todo_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type TodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *TodoRequest) Reset() {
	*x = TodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoRequest) ProtoMessage() {}

func (x *TodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoRequest.ProtoReflect.Descriptor instead.
func (*TodoRequest) Descriptor() ([]byte, []int) {
	return file_models_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The response message containing the greetings
type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_todo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_models_todo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_models_todo_proto_rawDescGZIP(), []int{2}
}

func (x *Todo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TodoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *TodoResponse) Reset() {
	*x = TodoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_todo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoResponse) ProtoMessage() {}

func (x *TodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_todo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoResponse.ProtoReflect.Descriptor instead.
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return file_models_todo_proto_rawDescGZIP(), []int{3}
}

func (x *TodoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// the query by id
type TodoQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *TodoQuery) Reset() {
	*x = TodoQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_todo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoQuery) ProtoMessage() {}

func (x *TodoQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_todo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoQuery.ProtoReflect.Descriptor instead.
func (*TodoQuery) Descriptor() ([]byte, []int) {
	return file_models_todo_proto_rawDescGZIP(), []int{4}
}

func (x *TodoQuery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_models_todo_proto protoreflect.FileDescriptor

var file_models_todo_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x22, 0x06, 0x0a,
	0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x22, 0x2f, 0x0a, 0x0b, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x1e, 0x0a, 0x0c, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x1b, 0x0a, 0x09, 0x54, 0x6f, 0x64, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x32, 0xb6, 0x02,
	0x0a, 0x04, 0x74, 0x6f, 0x44, 0x6f, 0x12, 0x44, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x64, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x54, 0x6f,
	0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f,
	0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x13, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64,
	0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x0e, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x54, 0x6f, 0x64, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e,
	0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x75, 0x6c, 0x6c, 0x1a, 0x0e,
	0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x3b, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x42, 0x79, 0x49,
	0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x0e, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00, 0x12,
	0x35, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x1a, 0x0e, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61, 0x6e, 0x6b, 0x68, 0x61, 0x75, 0x73, 0x65, 0x72, 0x6c,
	0x69, 0x2f, 0x47, 0x4f, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x54,
	0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_todo_proto_rawDescOnce sync.Once
	file_models_todo_proto_rawDescData = file_models_todo_proto_rawDesc
)

func file_models_todo_proto_rawDescGZIP() []byte {
	file_models_todo_proto_rawDescOnce.Do(func() {
		file_models_todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_todo_proto_rawDescData)
	})
	return file_models_todo_proto_rawDescData
}

var file_models_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_todo_proto_goTypes = []any{
	(*Null)(nil),         // 0: TodoGrpc.null
	(*TodoRequest)(nil),  // 1: TodoGrpc.TodoRequest
	(*Todo)(nil),         // 2: TodoGrpc.Todo
	(*TodoResponse)(nil), // 3: TodoGrpc.TodoResponse
	(*TodoQuery)(nil),    // 4: TodoGrpc.TodoQuery
}
var file_models_todo_proto_depIdxs = []int32{
	1, // 0: TodoGrpc.toDo.createTodoService:input_type -> TodoGrpc.TodoRequest
	4, // 1: TodoGrpc.toDo.deleteTodoService:input_type -> TodoGrpc.TodoQuery
	0, // 2: TodoGrpc.toDo.getAllTodosService:input_type -> TodoGrpc.null
	4, // 3: TodoGrpc.toDo.getTodoByIDService:input_type -> TodoGrpc.TodoQuery
	2, // 4: TodoGrpc.toDo.updateTodoService:input_type -> TodoGrpc.Todo
	3, // 5: TodoGrpc.toDo.createTodoService:output_type -> TodoGrpc.TodoResponse
	2, // 6: TodoGrpc.toDo.deleteTodoService:output_type -> TodoGrpc.Todo
	2, // 7: TodoGrpc.toDo.getAllTodosService:output_type -> TodoGrpc.Todo
	2, // 8: TodoGrpc.toDo.getTodoByIDService:output_type -> TodoGrpc.Todo
	2, // 9: TodoGrpc.toDo.updateTodoService:output_type -> TodoGrpc.Todo
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_todo_proto_init() }
func file_models_todo_proto_init() {
	if File_models_todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_todo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_todo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_todo_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_todo_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TodoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_todo_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TodoQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_todo_proto_goTypes,
		DependencyIndexes: file_models_todo_proto_depIdxs,
		MessageInfos:      file_models_todo_proto_msgTypes,
	}.Build()
	File_models_todo_proto = out.File
	file_models_todo_proto_rawDesc = nil
	file_models_todo_proto_goTypes = nil
	file_models_todo_proto_depIdxs = nil
}
